# Generated by Django 2.0.6 on 2018-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180706_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='state',
            name='state_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
