# Generated by Django 2.0.6 on 2018-07-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slack_userid',
            new_name='slack_id',
        ),
    ]
