# Generated by Django 2.0.6 on 2018-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180707_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=32),
        ),
    ]
