# Generated by Django 2.0.6 on 2018-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_state_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
